# see: https://raw.githubusercontent.com/mtpereira/parede/fb38213a8dbdf98daffe35c895df14d05afe5e2b/.github/workflows/preview.yml
name: tool
on: [push]
  pull_request:
    branches:
      - master
      - releases/*
  push:
    branches:
      - master
      - releases/*
jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    env:
      GOOS: go env GOOS
      GOARCH: go env GOARCH

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout this commit
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: move gsheet
        run: cd tool/googlesheet
      
      - name: build gsheet
        run: env GOOS=GOOS GOARCH=GOARCH go build . && mv ./googlesheet ../../
      
      - name: list
        run: ./googlesheet -option=hugo
      

      
