name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: tools
      uses: cedrickring/golang-action@1.4.1
      with:
        args: make dev.tools